{{- if .Values.monitoring.loki.datasource.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-crud-app.fullname" . }}-loki-datasource
  namespace: {{ .Values.monitoring.loki.datasource.grafanaNamespace }}
  labels:
    {{- include "simple-crud-app.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: {{ .Values.monitoring.loki.datasource.url }}
        isDefault: false
        editable: true
{{- end }}
