apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-crud-app-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # TODO: Replace with your Git repo URL
    repoURL: https://github.com/<your-org>/simple_crud_app.git
    path: argocd/apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
