apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "cnpg-cluster.name" . }}
  labels:
    {{- include "cnpg-cluster.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.cluster.instances }}
  imageName: {{ .Values.cluster.imageName }}

  bootstrap:
    initdb:
      database: {{ .Values.cluster.database }}
      owner: {{ .Values.cluster.owner }}

  storage:
    size: {{ .Values.cluster.storage.size }}
    {{- if .Values.cluster.storage.storageClass }}
    storageClass: {{ .Values.cluster.storage.storageClass }}
    {{- end }}

  resources:
    {{- toYaml .Values.cluster.resources | nindent 4 }}

  {{- if .Values.cluster.monitoring.enabled }}
  monitoring:
    enablePodMonitor: true
  {{- end }}
