{{- if .Values.cluster.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "cnpg-cluster.name" . }}
  labels:
    {{- include "cnpg-cluster.labels" . | nindent 4 }}
    {{- with .Values.cluster.monitoring.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      cnpg.io/cluster: {{ include "cnpg-cluster.name" . }}
      cnpg.io/podRole: instance
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.cluster.monitoring.interval }}
{{- end }}
