apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/selvakumarperumal/simple_crud_app.git
    path: helm/cnpg-cluster
    targetRevision: HEAD
    helm:
      releaseName: crud-db
      valuesObject:
        cluster:
          instances: 1
          monitoring:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: crud
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jqPathExpressions:
        - .spec.monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
