apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crud-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/selvakumarperumal/simple_crud_app.git
    path: helm/simple-crud-app
    targetRevision: HEAD
    helm:
      releaseName: crud-app
      valueFiles:
        - values.yaml
      # --- Minikube overrides (remove for EKS) ---
      valuesObject:
        image:
          pullPolicy: Never        # EKS: remove or set to Always
        service:
          type: NodePort            # EKS: remove (uses ClusterIP default)
  destination:
    server: https://kubernetes.default.svc
    namespace: crud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
